kmod/vdpa: include missing header
Added missing header (linux/bitfield.h) to fix build on v6.8 kernel.

 error: implicit declaration of function _FIELD_GET_
 [-Werror=implicit-function-declaration]

Fixes: 3fc40523215b ("kmod/vdpa: correct VF mailbox data address
		     calculation")
Cc: schalla@marvell.com

Signed-off-by: Shijith Thotton <sthotton@marvell.com>
Change-Id: Ia62693db4d630f41c79a4e3558fef351deed4c19
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/dataplane/dpu-offload/+/142454
Tested-by: sa_ip-toolkits-Jenkins <sa_ip-toolkits-jenkins@marvell.com>
Reviewed-by: Srujana Challa <schalla@marvell.com>